### PR TITLE
Add the 'eof' operator

### LINKED ISSUE #37: Add a `eof` terminal
Is it possible to have

```
eof :: Prod r e t ()
```

that matches the end of input?

I have a grammar that accepts expressions in parentheses:

```
    exprInBrackets <- rule $
      ExprInBrackets
        <$> leftBrack
        <*> ntExpr
        <*> rightBrack
        <?> "parenthesized expression"
```

And, given `([2])` it will produce the following value:

```
let inner = ExprInBrackets "[" (ExprNum 2) "]"
in ExprInBrackets "(" inner ")"
```

I'd like to modify it like this:

```
    exprInBrackets <- rule $
      ExprInBrackets
        <$> leftParen
        <*> ntExpr
        <*> (rightParen <|> ("" <$ eof))
        <?> "parenthesized expression"
```

so that expressions with unbalanced parentheses can be parsed. Given `([2` it would produce

```
let inner = ExprInBrackets "[" (ExprNum 2) ""
in ExprInBrackets "(" inner ""
```

cc @artemohanjanyan

### PR DESCRIPTION
**Pull request by int-index**
closes #37

### CODE REVIEW

**Comment by phadej** [comment]
Eof should look a not like Terminal. Instead of some alphabet we now work with an alphabet amended with an "end-marker"(or infinitely many)

I haven't checked the tests, but there should be `eof *> eof *> eof` which IMHO should match an empty string.

**Comment by int-index** [comment]
> but there should be `eof *> eof *> eof` which IMHO should match an empty string.

@phadej It does, that's the only reason to have this feature at all. `Eof` can be matched infinitely many times, otherwise it would be equivalent to extending the set of tokens with a special marker and appending it at the end of input.

> `Eof` should look a not like Terminal.

In what sense and why?

**Comment by phadej** [comment]
Autocorrect, I meant "a lot"

**Comment by ollef** [comment]
`prodNulls` is supposed to return all the ways that a production can be parsed without consuming any input. This might be more complicated with EOFs though... `removeNulls` is the opposite, but conservative (so it doesn't matter as much), i.e. it should remove parts of a production that can only be parsed without consuming anything.

Building on what @phadej's saying, perhaps it's actually possible to achieve `eof` without special support for it by augmenting your input token string with infinitely many `EOF` tokens at the end.

**Comment by int-index** [comment]
>  by augmenting your input token string with infinitely many EOF tokens at the end

Perhaps I'm missing something, but an Earley parser can never succeed on an infinite input, as it tries to consume it entirely.

**Comment by ollef** [comment]
@int-index: It should stop if it's not able to continue parsing even if it hasn't consumed all of the input, which should be the case with infinitely many EOFs at the end. We'd have to use `allParses` instead of `fullParses` since `fullParses` only returns results that have consumed all of the input. And to make sure that you only get full parses (not including the infinitely many EOFs at the end), add an extra `eof` terminal at the very end of your full grammar.

If we can get this to work it might be a good example to add to the library.

**Comment by int-index** [comment]
I don't think I have time to finish this, I didn't anticipate the `eof' <- rule eof` issue and I don't know how to address it.

**Comment by ollef** [comment]
No worries! I might have a go at making an example using the current functionality at some point if no one else beats me to it.

**Comment by ollef** [comment]
I did that in https://github.com/ollef/Earley/pull/40, so I'll close this now. Cheers!

**Pull request closed without merging**
